# Generated by Django 6.0.5 on 2026-06-03 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3)], verbose_name="Ім'я")),
                ('initials', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Ініціали')),
                ('description', models.CharField(max_length=250, verbose_name='Опис')),
                ('role', models.CharField(choices=[('none', 'Unnamed Employee'), ('general_director', 'Генеральний директор'), ('technical_director', 'Технічний директор'), ('finance_director', 'Фінансовий директор'), ('main_architect', 'Головний архітектор')], default='none', max_length=20, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Роботник',
                'verbose_name_plural': 'Роботник',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Назва')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новина',
                'ordering': ['-publish_date', 'title'],
            },
        ),
    ]
