# Generated by Django 6.0.5 on 2026-05-27 21:49

import django.core.validators
import django.db.models.deletion
import locations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name="Ім'я")),
            ],
            options={
                'verbose_name': 'Сторож',
                'verbose_name_plural': 'Сторожі',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('is_portal_open', models.BooleanField(default=True, verbose_name='Портал відчинений')),
                ('work_starts_at', models.TimeField(verbose_name='Дата початку роботи')),
                ('finish_work_at', models.TimeField(verbose_name='Дата завершення роботи')),
                ('image', models.ImageField(blank=True, null=True, upload_to=locations.models.image_upload_path, verbose_name='Фото')),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='locations.guardian', verbose_name='Сторож')),
            ],
            options={
                'verbose_name': 'Локація',
                'verbose_name_plural': 'Локації',
                'ordering': ['name'],
            },
        ),
    ]
