# Generated by Django 6.0.5 on 2026-05-27 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_guardian_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='secret_password',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(regex='^[а-яА-Я]{10,20}$')], verbose_name='Секретний пароль'),
        ),
    ]
